/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Ricardo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    public Main(){
        initComponents();
    }
    
    int nuevoid;
    String nuevousuario;
    String nuevorol;
    
    public Main(int id, String usuario, String rol) {
        initComponents();
        
        this.nuevousuario = usuario;
        usuarioLabel.setText(nuevousuario);
        this.nuevorol = rol;
        rolLabel.setText(nuevorol);
        this.nuevoid = id;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pacientesButton = new javax.swing.JButton();
        doctoresButton = new javax.swing.JButton();
        crearCitasBtn = new javax.swing.JButton();
        verCitasButton = new javax.swing.JButton();
        prescripcionButton = new javax.swing.JButton();
        activosButton = new javax.swing.JButton();
        crearUsuarioButton = new javax.swing.JButton();
        verDoctorButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        pacientesButton1 = new javax.swing.JButton();
        pacientesButton2 = new javax.swing.JButton();
        pacientesButton3 = new javax.swing.JButton();
        prescripcionButton1 = new javax.swing.JButton();
        prescripcionButton2 = new javax.swing.JButton();
        hospitalLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        rolLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        pacientesButton.setText("Pacientes");
        pacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButtonActionPerformed(evt);
            }
        });

        doctoresButton.setText("Doctores");
        doctoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctoresButtonActionPerformed(evt);
            }
        });

        crearCitasBtn.setText("Crear citas");
        crearCitasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCitasBtnActionPerformed(evt);
            }
        });

        verCitasButton.setText("Ver Citas");
        verCitasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCitasButtonActionPerformed(evt);
            }
        });

        prescripcionButton.setText("Prescripcion");
        prescripcionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescripcionButtonActionPerformed(evt);
            }
        });

        activosButton.setText("Activos");
        activosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activosButtonActionPerformed(evt);
            }
        });

        crearUsuarioButton.setText("Crear usuario");
        crearUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioButtonActionPerformed(evt);
            }
        });

        verDoctorButton.setText("Ver Doctor");
        verDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDoctorButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        pacientesButton1.setText("Hospitales");
        pacientesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButton1ActionPerformed(evt);
            }
        });

        pacientesButton2.setText("Pagos");
        pacientesButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButton2ActionPerformed(evt);
            }
        });

        pacientesButton3.setText("Cita PostOperatoria");
        pacientesButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButton3ActionPerformed(evt);
            }
        });

        prescripcionButton1.setText("Internamientos");
        prescripcionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescripcionButton1ActionPerformed(evt);
            }
        });

        prescripcionButton2.setText("Cirugias");
        prescripcionButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescripcionButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pacientesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doctoresButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pacientesButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pacientesButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(crearCitasBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(verCitasButton))
                    .addComponent(pacientesButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prescripcionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(activosButton))
                    .addComponent(prescripcionButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prescripcionButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crearUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacientesButton)
                    .addComponent(doctoresButton)
                    .addComponent(crearCitasBtn)
                    .addComponent(verCitasButton)
                    .addComponent(prescripcionButton)
                    .addComponent(activosButton)
                    .addComponent(crearUsuarioButton)
                    .addComponent(verDoctorButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pacientesButton1)
                    .addComponent(pacientesButton2)
                    .addComponent(pacientesButton3)
                    .addComponent(prescripcionButton1)
                    .addComponent(prescripcionButton2)
                    .addComponent(logoutButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        hospitalLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        hospitalLabel.setText("Proyecto Hospital");

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario: ");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rol: ");

        usuarioLabel.setBackground(new java.awt.Color(255, 255, 255));
        usuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        usuarioLabel.setText("jLabel3");

        rolLabel.setBackground(new java.awt.Color(255, 255, 255));
        rolLabel.setForeground(new java.awt.Color(255, 255, 255));
        rolLabel.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rolLabel)
                    .addComponent(usuarioLabel))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rolLabel))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(hospitalLabel)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hospitalLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientesButtonActionPerformed

    private void doctoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctoresButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctoresButtonActionPerformed

    private void crearCitasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCitasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCitasBtnActionPerformed

    private void verCitasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCitasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verCitasButtonActionPerformed

    private void prescripcionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescripcionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prescripcionButtonActionPerformed

    private void activosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activosButtonActionPerformed

    private void crearUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioButtonActionPerformed
        
            Usuario usuario = new Usuario();
            usuario.setVisible(true);
    }//GEN-LAST:event_crearUsuarioButtonActionPerformed

    private void verDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDoctorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verDoctorButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void pacientesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientesButton1ActionPerformed

    private void pacientesButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientesButton2ActionPerformed

    private void pacientesButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientesButton3ActionPerformed

    private void prescripcionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescripcionButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prescripcionButton1ActionPerformed

    private void prescripcionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescripcionButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prescripcionButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activosButton;
    private javax.swing.JButton crearCitasBtn;
    private javax.swing.JButton crearUsuarioButton;
    private javax.swing.JButton doctoresButton;
    private javax.swing.JLabel hospitalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton pacientesButton;
    private javax.swing.JButton pacientesButton1;
    private javax.swing.JButton pacientesButton2;
    private javax.swing.JButton pacientesButton3;
    private javax.swing.JButton prescripcionButton;
    private javax.swing.JButton prescripcionButton1;
    private javax.swing.JButton prescripcionButton2;
    private javax.swing.JLabel rolLabel;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JButton verCitasButton;
    private javax.swing.JButton verDoctorButton;
    // End of variables declaration//GEN-END:variables
}
