/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ricardo
 */
public class Paciente extends javax.swing.JFrame {

    /**
     * Creates new form Paciente
     */
    public Paciente() {
        initComponents();
        Conexion();
        TablaPaciente();
    }
    
    Connection conexion;
    PreparedStatement preparedStatement;
    ResultSet resultset;
    
    public void Conexion(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/proyectohospital?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT","root","");
            //conexion = DriverManager.getConnection("jdbc:mysql://localhost:3307/proyectohospital?autoReconnect=true&useSSL=false","root","");
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void TablaPaciente(){
        try {
            preparedStatement = conexion.prepareStatement("select * from pacientes");
            resultset = preparedStatement.executeQuery();
            java.sql.ResultSetMetaData Rsm = resultset.getMetaData();
            int conteoColumna;
            conteoColumna = Rsm.getColumnCount();
            DefaultTableModel defaultTable = (DefaultTableModel)tablaPacientes.getModel();
            defaultTable.setRowCount(0);
            
            while(resultset.next()){
                Vector vector = new Vector();
                
                for (int indiceColumna = 0; indiceColumna < conteoColumna; indiceColumna++) {
                    vector.add(resultset.getString("id_paciente"));
                    vector.add(resultset.getString("cedula"));
                    vector.add(resultset.getString("primer_apellido"));
                    vector.add(resultset.getString("segundo_apellido"));
                    vector.add(resultset.getString("nombre"));
                    vector.add(resultset.getString("telefono"));
                    vector.add(resultset.getString("estado_civil"));
                    vector.add(resultset.getString("correo"));
                    vector.add(resultset.getString("estado_paciente"));
                }
                defaultTable.addRow(vector);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Paciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cedulaPacienteText = new javax.swing.JTextField();
        nombrePacienteText = new javax.swing.JTextField();
        apellido1PacienteText = new javax.swing.JTextField();
        apellido2PacienteText = new javax.swing.JTextField();
        correoPacienteText = new javax.swing.JTextField();
        telefonoPacienteText = new javax.swing.JTextField();
        estadoCivilPacienteCombobox = new javax.swing.JComboBox<>();
        estadoPacienteCombobox = new javax.swing.JComboBox<>();
        jlabel = new javax.swing.JLabel();
        idPacienteLabel = new javax.swing.JLabel();
        agregarPacienteButton = new javax.swing.JButton();
        actualizarPacienteButton = new javax.swing.JButton();
        eliminarPacienteButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Primer apellido");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Segundo apellido");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado civil");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado");

        apellido2PacienteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido2PacienteTextActionPerformed(evt);
            }
        });

        estadoCivilPacienteCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero(a)", "Casado(a)" }));

        estadoPacienteCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        jlabel.setText("ID Paciente: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(correoPacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(telefonoPacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cedulaPacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellido1PacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(52, 52, 52)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(estadoCivilPacienteCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apellido2PacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(estadoPacienteCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombrePacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPacienteLabel)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel)
                    .addComponent(idPacienteLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cedulaPacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nombrePacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(apellido1PacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido2PacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(correoPacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilPacienteCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(telefonoPacienteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoPacienteCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        agregarPacienteButton.setText("Agregar");
        agregarPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPacienteButtonActionPerformed(evt);
            }
        });

        actualizarPacienteButton.setText("Actualizar");
        actualizarPacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPacienteButtonActionPerformed(evt);
            }
        });

        eliminarPacienteButton.setText("Eliminar");

        salirButton.setText("Salir");

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente N°", "Cedula", "Nombre", "Primer apellido", "Segundo apellido", "Telefono", "Estado civil", "Correo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPacientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(agregarPacienteButton)
                        .addGap(46, 46, 46)
                        .addComponent(actualizarPacienteButton)
                        .addGap(50, 50, 50)
                        .addComponent(eliminarPacienteButton)
                        .addGap(47, 47, 47)
                        .addComponent(salirButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarPacienteButton)
                    .addComponent(actualizarPacienteButton)
                    .addComponent(eliminarPacienteButton)
                    .addComponent(salirButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPacienteButtonActionPerformed
        int cedulaPaciente = Integer.parseInt(cedulaPacienteText.getText());
        String nombrePaciente = nombrePacienteText.getText();
        String apellido1Paciente = apellido1PacienteText.getText();
        String apellido2Paciente = apellido2PacienteText.getText();
        int telefonoPaciente = Integer.parseInt(telefonoPacienteText.getText());
        String estadoCivilPaciente = estadoCivilPacienteCombobox.getSelectedItem().toString();
        String correoPaciente = correoPacienteText.getText();
        String estadoPaciente = estadoPacienteCombobox.getSelectedItem().toString();
        
        Conexion();
        try {
            preparedStatement = conexion.prepareStatement("insert into pacientes(cedula,primer_apellido,segundo_apellido,nombre,telefono,estado_civil,correo,estado_paciente)values(?,?,?,?,?,?,?,?)");
            preparedStatement.setInt(1,cedulaPaciente);
            preparedStatement.setString(2, apellido1Paciente);
            preparedStatement.setString(3, apellido2Paciente); 
            preparedStatement.setString(4,nombrePaciente);
            preparedStatement.setInt(5, telefonoPaciente);
            preparedStatement.setString(6, estadoCivilPaciente);
            preparedStatement.setString(7, correoPaciente);
            preparedStatement.setString(8, estadoPaciente);
            preparedStatement.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Paciente ingresado");
            
            cedulaPacienteText.setText("");
            nombrePacienteText.setText("");
            apellido1PacienteText.setText("");
            apellido2PacienteText.setText("");
            estadoCivilPacienteCombobox.setSelectedIndex(-1);
            telefonoPacienteText.setText("");
            estadoPacienteCombobox.setSelectedIndex(-1);
            correoPacienteText.setText("");
            cedulaPacienteText.requestFocus();
            TablaPaciente();
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_agregarPacienteButtonActionPerformed

    private void apellido2PacienteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido2PacienteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellido2PacienteTextActionPerformed

    private void tablaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPacientesMouseClicked
        DefaultTableModel defaultPaciente = (DefaultTableModel)tablaPacientes.getModel();
        int SelectIndex = tablaPacientes.getSelectedRow();
        
        idPacienteLabel.setText(defaultPaciente.getValueAt(SelectIndex, 0).toString());
        cedulaPacienteText.setText(defaultPaciente.getValueAt(SelectIndex, 1).toString());
        nombrePacienteText.setText(defaultPaciente.getValueAt(SelectIndex, 2).toString());
        apellido1PacienteText.setText(defaultPaciente.getValueAt(SelectIndex, 3).toString());
        apellido2PacienteText.setText(defaultPaciente.getValueAt(SelectIndex, 4).toString());
        telefonoPacienteText.setText(defaultPaciente.getValueAt(SelectIndex, 5).toString());
        estadoCivilPacienteCombobox.setSelectedItem(defaultPaciente.getValueAt(SelectIndex, 6).toString());
        correoPacienteText.setText(defaultPaciente.getValueAt(SelectIndex, 7).toString());
        estadoPacienteCombobox.setSelectedItem(defaultPaciente.getValueAt(SelectIndex, 8).toString());
        agregarPacienteButton.setEnabled(false);
    }//GEN-LAST:event_tablaPacientesMouseClicked

    private void actualizarPacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPacienteButtonActionPerformed
        int cedulaPaciente = Integer.parseInt(cedulaPacienteText.getText());
        String apellido1Paciente = apellido1PacienteText.getText();
        String apellido2Paciente = apellido2PacienteText.getText();
        String nombrePaciente = nombrePacienteText.getText();
        String telefonoPaciente = telefonoPacienteText.getText();
        String estadoCivilPaciente = estadoCivilPacienteCombobox.getSelectedItem().toString();
        String correoPaciente = correoPacienteText.getText();
        String estadoPaciente = estadoPacienteCombobox.getSelectedItem().toString();
        int idPaciente = Integer.parseInt(idPacienteLabel.getText());
        
        Conexion();
        try {
            preparedStatement = conexion.prepareStatement("update pacientes set cedula = ?,primer_apellido = ?,segundo_apellido = ?,nombre = ?,telefono = ?,estado_civil = ?,correo = ?,estado_paciente = ? where id_paciente = ?");
            preparedStatement.setInt(1,cedulaPaciente);
            preparedStatement.setString(2, apellido1Paciente);
            preparedStatement.setString(3, apellido2Paciente); 
            preparedStatement.setString(4,nombrePaciente);
            preparedStatement.setString(5, telefonoPaciente);
            preparedStatement.setString(6, estadoCivilPaciente);
            preparedStatement.setString(7, correoPaciente);
            preparedStatement.setString(8, estadoPaciente);
            preparedStatement.setInt(9, idPaciente);
            preparedStatement.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Paciente actualizado");
            
            idPacienteLabel.setText("");
            cedulaPacienteText.setText("");
            nombrePacienteText.setText("");
            apellido1PacienteText.setText("");
            apellido2PacienteText.setText("");
            estadoCivilPacienteCombobox.setSelectedIndex(-1);
            telefonoPacienteText.setText("");
            estadoPacienteCombobox.setSelectedIndex(-1);
            correoPacienteText.setText("");
            cedulaPacienteText.requestFocus();
            TablaPaciente();
            agregarPacienteButton.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_actualizarPacienteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarPacienteButton;
    private javax.swing.JButton agregarPacienteButton;
    private javax.swing.JTextField apellido1PacienteText;
    private javax.swing.JTextField apellido2PacienteText;
    private javax.swing.JTextField cedulaPacienteText;
    private javax.swing.JTextField correoPacienteText;
    private javax.swing.JButton eliminarPacienteButton;
    private javax.swing.JComboBox<String> estadoCivilPacienteCombobox;
    private javax.swing.JComboBox<String> estadoPacienteCombobox;
    private javax.swing.JLabel idPacienteLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField nombrePacienteText;
    private javax.swing.JButton salirButton;
    private javax.swing.JTable tablaPacientes;
    private javax.swing.JTextField telefonoPacienteText;
    // End of variables declaration//GEN-END:variables
}
